### ISSUE TITLE
Import file

### ISSUE THREAD

**Issue by githubnagib** [mpetroff/qgsazimuth#10]
What type of files should be made to imported azimuths and distance?
msgbox: Invalid input

**Comment by mpetroff** [comment]
It's designed to import the plugin's exported segment lists. Export a segment list and look at its format.

**Comment by leandrolelo** [comment]
Hello
I'm trying to submit a list of azimuths and distances in the plugin, but I can not because I do not know what the best data format it requires. I tried to add the data one by one and then export the list. But always, in both situations, returns the following error:

An error occurred while performing the following Python code:

Traceback (most recent call last):
  File "C: /Users/Leandro/.qgis//python/plugins \ qgsAzimuth \ qgsAzimuth.py", line 442, in loadList
    if not os.path.exists (self.fileName):
  File "C: \ PROGRA ~ 2 \ Quantum GIS Lisboa \ apps \ python27 \ lib \ genericpath.py", line 18, in exists
    os.stat (path)
UnicodeDecodeError: 'ascii' codec can not decode byte 0xe3 in position 40: ordinal not in range (128)

Python version:
2.7.2 (default, 12 Jun 2011 15:08:59) [v.1500 MSC 32 bit (Intel)]


QGIS version
1.8.0-Lisbon, f440b60

Path to Python: [ 'C: \\ Users \\ \\ Leandro qgis python \\ \\ \\ elevation plugins.', 'C: / PROGRA ~ 2 / Quantum GIS Lisboa / apps / qgis /./ python' 'C: /Users/Leandro/.qgis//python', 'C: /Users/Leandro/.qgis//python/plugins',' C: / PROGRA ~ 2 / Quantum GIS Lisboa / apps / qgis /. / python / plugins ',' C: \\ Program Files (x86) \\ \\ bin ArcGIS ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ bin \\ python27.zip ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ Apps \\ \\ python27 DLLs ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ lib \\ python27 ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ Apps \\ \\ lib \\ python27 plat-win ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ lib \\ python27 lib- tk ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ qgis bin ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ python27 ',' C : \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ lib \\ python27 site-packages ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ python27 \\ lib \ \ site-packages \\ PIL ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ lib \\ python27 site-packages \\ win32 ',' C: \\ PROGRA ~ 2 \ \ Quantum GIS Lisboa \\ apps \\ \\ lib \\ python27 site-packages \\ lib \\ win32 ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ lib \\ python27 site-packages Pythonwin \\ ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ lib \\ python27 site-packages \\ wx-2.8-msw-unicode ',' / usr / share / qgis / python ',' C: \\ PROGRA ~ 2 \\ Quantum GIS Lisboa \\ apps \\ \\ qgis python plugins \\ \\ \\ fTools tools']

Am I doing something wrong?

Grateful for the attention!

**Comment by mpetroff** [comment]
`UnicodeDecodeError: 'ascii' codec can not decode byte 0xe3 in position 40: ordinal not in range (128)`: You're using a non-ASCII character, which aren't supported.

**Comment by leandrolelo** [comment]
OK, thank's for attention.

**Comment by mpetroff** [comment]
The person who opened this issue never replied, so I'm closing it.
