### ISSUE TITLE
Code from Qgis repository not matches with github

### ISSUE THREAD

**Issue by kylefelipe** [mpetroff/qgsazimuth#24]
After solve the issue #23 as you said, i had an other issue with plugins, this time Qgis was prompting that "Qgis.Polygon" does not exist.

So i compare qgsAzimuth.py from qgis repository with github, and i found that both codes are not the same.

![image](https://user-images.githubusercontent.com/24795382/64314366-28958b80-cf85-11e9-8cfc-3f82e9c3e3be.png)

On the left side, Line 616 (Github) and right side, line 618 (plugins.qgis.org), those 2 lines are different. 
And, with github code, i dont need to insert that import from the #23.

**Comment by mpetroff** [comment]
This is what happens when other people decide to email me instead of using this issue tracker. Someone emailed me in April about problems with plotting to polygon layers and some sort of import issue. I fixed the polygon layer issue, which is the code difference, and then asked a follow up question about the import issue. I was going to wait until both issues were fixed before pushing a new version, but the person never responded, and I forgot about it.

Anyway, I just uploaded v0.9.14 to the QGIS plugins repository with the fix. It will be available once the update is approved by a moderator.
