### ISSUE TITLE
Import Bug

### ISSUE THREAD

**Issue by Thanduel** [mpetroff/qgsazimuth#30]
Hi

At the moment if you try to import a segmented list using the radial option the import fails with invalid input.   This is due to the following bug:

On line 846 of qgsAzimuth.py in the method setSurvey

The radio button referred to as "radioButton_irrSurvey" should be "radioButton_radialSurvey"

```
def setSurvey(self, s):
    # self.say('processing surveyType='+s)
    if s == "polygonal":
        self.pluginGui.radioButton_boundarySurvey.setChecked(True)
    elif s == "radial":
        self.pluginGui.radioButton_irrSurvey.setChecked(True)
    else:
        self.say("invalid survey type: " + s)
```

Thanks for a great plugin.

**Comment by mpetroff** [comment]
It looks like it's been broken since v0.8.4 released in 2010, from before I ported this plugin to QGIS 2.0 and took over maintenance.

I just fixed it and upload a v0.9.16 release, which is currently waiting for approval in the plugin repository.

Sorry for taking so long to get to this. I was working in Antarctica when you opened this issue, and it fell through the cracks.
